"""Initial schema

Revision ID: a61046df6047
Revises: 
Create Date: 2026-06-15 15:54:14.318306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a61046df6047'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_contact', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_in', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_in', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('index_user_username', 'users', ['username'], unique=False)
    op.create_table('plcs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('port_modbus', sa.Integer(), nullable=False),
    sa.Column('port_tcp', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_in', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_plc_device_id', 'plcs', ['device_id'], unique=False)
    op.create_table('publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.Column('confirmed_in', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_pub_mid', 'publications', ['mid'], unique=False)
    op.create_table('received_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('retain', sa.Boolean(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('user_props', sa.Text(), nullable=True),
    sa.Column('received_in', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('index_msg_device_id', 'received_messages', ['device_id'], unique=False)
    op.create_index('index_msg_topic', 'received_messages', ['topic'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('index_reftokens_token_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('index_reftokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('map_registers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plc_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('tag_name', sa.String(length=30), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('scale', sa.Float(), nullable=False),
    sa.Column('offset', sa.Float(), nullable=False),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('read_only', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_in', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plc_id'], ['plcs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plc_id', 'type', 'address', name='uq_register_plc_type_address')
    )
    op.create_index('index_register,topic', 'map_registers', ['topic'], unique=False)
    op.create_index('index_register_plc_id', 'map_registers', ['plc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('index_register_plc_id', table_name='map_registers')
    op.drop_index('index_register,topic', table_name='map_registers')
    op.drop_table('map_registers')
    op.drop_index('index_reftokens_user_id', table_name='refresh_tokens')
    op.drop_index('index_reftokens_token_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('index_msg_topic', table_name='received_messages')
    op.drop_index('index_msg_device_id', table_name='received_messages')
    op.drop_table('received_messages')
    op.drop_index('index_pub_mid', table_name='publications')
    op.drop_table('publications')
    op.drop_index('index_plc_device_id', table_name='plcs')
    op.drop_table('plcs')
    op.drop_index('index_user_username', table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
